dist: bionic
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
  sonarcloud:
    organization: "kkweon"
    token:
      secure: "r83BmPunHgql7QiebJooUPML3GGe6cw4yaDS5PpydNxVHA2wQGPgM6famYg+Vi0oqZI5ZXO3BzKphVd+WWdE1XrwXOWdz5k8C5Bh20Qel35WXqvUrm5kIRTJk/jRizn7i/Eeym4zqnl/elSi6jWF6kSVuqUYy5O7iXV8wvRGB4dAZcC6jv30nvLpQwDlXZgVpXfzsNq5gJNqrmoLjxzgGTBxo5cLLa8jEabMXd93K9dNPaT9/wfIZJUDEONHYvdiLRtp+sKPB8erOa4Ui7ajagwkGEW16oJE8dOrq7ydSt0z1WWEHe/GiTetwHqfCQdROw4aRgWYdQy8KRrUB4uGx2LJmmdKClw80N/zldo8L6C4k55Lk6QAt8SLq61k4baw/HAl0HWpo9PO5sAzXsZEHMgUighjQ20WF+QWJggGZIcI7krfHLVsJ6fzUKANdfGT8hfknyJO8UT6Eyz8ZuoCM03YYnaPlwxN2v68NTvr2SGylTz65scljnhwfWbdPF+8wyMVM6pLBPBhKfoBzo9NU1QdPT7lxUP0zWKiWMEajUcBo1Zp3CmZWoIyFNZmUrHnnGMVB6uAVKpi1ea3F/zYiTa6UXMAZS5ACQTRZk2mG/fgByw9Y+zaM8o+ib7mHY0Vp3SuiwEEcxNLlwmlrnUECEwE9evCuhVKLt1qjKLABKg="

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
- sonar-scanner
