dist: bionic
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
  sonarcloud:
    organization: "kkweon"
    token:
      secure: "PCywzv48SQU1zkKyC3KOuYJB8bGrYwpmsnQCRCj+muDH6KnViAc+p7NEoFuYrFuiudAdgkOOY66LpEL33+IP+Q3qLidQIXBfE7EvM/NpCzB/gKvAA6A1FOFv5iWhH/lxtojQyZLzgQBxYnFnM6ANQaxAg4ufneiSXL05/mrwKFmLyPgtJ1C+Lz4jWECMRNIWXyKh6W9MZSYI8CFemrm//TSChm+5xyLLYf3pYNx3ohsC3cIkTuYnHJ6M1ZVz/OtoMz+bEkRGyAXGDfoeqId9u8t2Y3FPURIQHbmFq1/Yf+SgmDfiLqy9Ntge1aIRwqBMtYteUEkyx1W/+QcwKeeeTfYd/jWQEQHJxU+Nq8l7zVN6fXEd3iQ1RAUg2Ya7crG2Vc9SnzrU9vvmrqQWC8Xzv79FZXavyW18SeFOGGTmnAOYatepPrj+fmUqcdv7lYpboxUsEMw/TNQsP2gWm3rJdROLec800LqeOup9ca3eDkTYOGC7UYpith/ZTxjsWp8lZb/Rn9zX3t4oU/gEXJBfSURFZevT8iqQMWiPISvyQUmhd6hOYdWdd0Sjf9CV30UA4494i/MqiNhm5srr0KCwBhyrb5MoOgFNAi3+gdWCmmSvjEdMzbf2PBxLDraSUDJjSDINfm7Ql8RGWexC/JH++TVGokEbWgLSjzzn3OnAnDM="

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
- sonar-scanner
