name: holiday-service
version: 0.1.0.0
github: 'kkweon/holiday-service'
license: GPL-3
author: 'Kyung Mo Kweon'
maintainer: 'kkweon@gmail.com'
copyright: '2019 Kyung Mo Kweon'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kkweon/holiday-service#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - extra
  - time
  - korea-holidays
  - usa-holidays
  - linklater
  - wai
  - warp
  - text

library:
  source-dirs: src

executables:
  holiday-service-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - holiday-service

tests:
  holiday-service-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - holiday-service
      - hspec
